version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - PORT=8080
      - HEADLESS=1
    restart: unless-stopped
    # Uncomment to mount code for rapid backend iteration (dev only)
    # volumes:
    #   - ./backend:/app/backend
    #   - ./frontend/dist:/app/frontend_dist:ro
